CREATE TABLE [dbo].[monta](
	[id] [int] NOT NULL,
	[charge_point] [nvarchar](50) NOT NULL,
	[charge_point_id] [int] NOT NULL,
	[User] [nvarchar](50) NOT NULL,
	[Team] [nvarchar](50) NOT NULL,
	[state] [nvarchar](50) NOT NULL,
	[failed_reason] [nvarchar](1) NULL,
	[kwh] [float] NULL,
	[meter_start_kwh] [nvarchar](1) NULL,
	[meter_end_kwh] [float] NULL,
	[price] [nvarchar](1) NULL,
	[payment_method] [nvarchar](50) NOT NULL,
	[charge_key_name] [nvarchar](1) NULL,
	[created_at] [datetime2](7) NOT NULL,
	[starting_at] [datetime2](7) NULL,
	[completed_at] [datetime2](7) NOT NULL,
	[fully_charged_at] [nvarchar](50) NULL,
	[start_source] [nvarchar](50) NOT NULL,
	[start_meter_kwh] [nvarchar](1) NULL,
	[end_meter_kwh] [float] NULL,
	[co2] [float] NULL,
	[avg_co2_kwh] [float] NULL,
	[kwhs] [nvarchar](1050) NOT NULL,
	[note] [nvarchar](1) NULL
) ON [PRIMARY]
