CREATE TABLE [dbo].[PricesSubscriptions](
	[subscriptionId] [nvarchar](50) NULL,
	[name] [nvarchar](50) NULL,
	[description] [nvarchar](1000) NULL,
	[owner] [nvarchar](50) NULL,
	[validFromDate] [nvarchar](50) NULL,
	[validToDate] [nvarchar](50) NULL,
	[price] [nvarchar](50) NULL,
	[quantity] [nvarchar](50) NULL,
	[result_Id] [nvarchar](50) NULL
) ON [PRIMARY]
